### ISSUE TITLE
Issue: function epoch_data()

### ISSUE THREAD

**Issue by DrCri95** [craddm/eegUtils#108]
Hi,

First of all, thanks a lot for this R package, really useful!

I've been preprocessing EEG data (n = 40 participants) and everything is okay for 38 datasets.
However, I got this error in 2 datasets when extracting epochs. 
I've been reviewing these 2 files in more detail and I could not find any issue within these datasets (correct events, correct signals, and so on).

```
epoch_data(eeg_data, events = c(55, 56), epoch_labels = c("right","left"), time_lim = c(-0.2, 3.0), baseline = c(-.2, 0))

Error in dim(base_times$signals) <- c(n_bl_times, n_epochs, n_chans) : 
  dims [product 3336216] do not match the length of object [3329280]
```
Thanks!

**Comment by craddm** [comment]
This might be fixed on the dev branch now.

Matt

**Comment by DrCri95** [comment]
Hi Matt,

Thank you very much for your quick response!

Until today I have not been able to do the checks you have suggested.
The good news is that my problem has been solved, I have extracted the epochs without getting any errors, after having installed the latest development version.

Cheers,
Cris
