### ISSUE TITLE
compute_tfr() function

### ISSUE THREAD

**Issue by DrCri95** [craddm/eegUtils#110]
Hi,

I'm computing time-frequency representation of my EEG data:
```
tfr <- compute_tfr (data,
                          method = "morlet",
                          foi = c (4, 30),
                          n_freq = 12,
                          n_cycles = 3)
```

and I got the following error:

> Error in dim (data $ signals) <- c (n_times, n_epochs, n_chans):
>    dims [product 13127264] do not match the length of object [215153632]

Before reporting this issue, I've checked my data (large eeg_epochs) and installed the latest development version from Github, since the last time I got a similar error extracting epochs, my issue was actually solved after installing the latest development version.

Thank you very much in advance!

Best,
Cris

**Comment by craddm** [comment]
Closing this one for now as this may have been a workflow issue rather than a `eegUtils` issue per se
