### ISSUE TITLE
question: how to use topoplot function with preprocessed data?

### ISSUE THREAD

**Issue by Ali-Mahdipour** [craddm/eegUtils#130]
I have a data frame of EEG powers (amplitude) with their channel names (10-20 system) and I want to use topoplot function to plot this data. I read in the documentation of the topoplot function that this should be possible if I pass the data frame to the function. Could you provide a minimal example of how this can be done. What structure should the data frame follow?

**Comment by craddm** [comment]
`topoplot()` needs four columns in a `data.frame` - `electrode`, `x`, `y`, and `amplitude`. 

``` r
library(eegUtils)
#> 
#> Attaching package: 'eegUtils'
#> The following object is masked from 'package:stats':
#> 
#>     filter
library(tidyverse)
as.data.frame(demo_spatial, long = TRUE) %>%
  select(electrode, x, y, amplitude) %>%
  topoplot()
#> Using electrode locations from data.
#> Removing channels with no location.
#> Plotting head r 95 mm
```

![](https://i.imgur.com/Q8exIW9.png)

<sup>Created on 2022-09-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


If you don't have `x` and `y` coordinates for your electrodes, you can try adding standard locations with the function `electrode_locations()`.
