### ISSUE TITLE
topoplot does not scale

### ISSUE THREAD

**Issue by themeo** [craddm/eegUtils#17]
Topoplots are a great feature of eegUtils, but forcing them to look nice on a 5x5cm figure is a pain (requires hacks using ggplot_build() / ggplot_gtable()). It would be great if topoplot had an optional argument with a scaling factor and have all line weights in contours be based on this factor.

**Comment by craddm** [comment]
@themeo the first thing I noticed was I hadn't set the contour lines to scale at all, unlike everything else, but even doing that didn't seem to help a lot. So, I've added a scaling argument that scales *all* lines + labels. See how you get on with that...

**Comment by themeo** [comment]
Hi, thanks for the scaling parameter - it is very useful indeed! (and sorry for a rather late reply...). I still have one issue with scaling. When I set scaling to 0.5, the interpolation does not reach the farthest electrodes (I use the standard 10/5 system) and the plotted head. Playing with different values of `r` does not help. Setting `interp_limit` to "head" makes things even worse. 
![Fig 9b exp2](https://user-images.githubusercontent.com/2484158/59870392-18451b80-935b-11e9-8a76-3a1e2abc9c51.png)

**Comment by craddm** [comment]
it'll be the masking ring that causes the problem; i'll try to make that more configurable, but I'll also try to sort out a function exposing the interpolated grid to make it easier to interface with standard ggplot geoms. Building the topoplot up manually, as per https://craddm.github.io/eegUtils/articles/topoplot.html helps with some issues, but geom_contour() is a bit of a pain for that approach...

The only awkward part with th
