### ISSUE TITLE
Submit to Neuroconductor

### ISSUE THREAD

**Issue by muschellij2** [craddm/eegUtils#20]
Dear Matt,
Love the package.  Any interest in submitting to Neuroconductor? It's a general medical image analysis  repo of R packages (similar to Bioconductor), and I think eegUtils would work well.    We have ports for FSL and neuroimaging things but nothing really for EEG.

https://neuroconductor.org/submit-package

@adigherman

**Comment by craddm** [comment]
Definitely interested - will make preparations...

**Comment by craddm** [comment]
done!
