### ISSUE TITLE
Plot ERPs on the scalp

### ISSUE THREAD

**Issue by mvuorre** [craddm/eegUtils#3]
Hi,

Any plans on implementing a function for a plot that shows a topographic arrangement of ERPs? I've been working on one [here](https://github.com/mvuorre/eegUtils/blob/dev/R/erp_scalp.R), and can send in a pull request if it's a feature you'd like to add to eegUtils.

Here's sample output from the function on my dev branch:
```
erp_scalp(data, color = "group")
```
![rplot](https://user-images.githubusercontent.com/7349270/28135647-f4365c1e-6714-11e7-909d-7e8637fbda36.png)

**Comment by craddm** [comment]
looks great. I was planning to try something along these lines so sure, fire up a pull request

**Comment by mvuorre** [comment]
I've sent a PR #4 but note that it also has an additional function for getting the default electrode locations AND I've updated the namespace to reflect these changes. I am happy to make any desired changes to the function(s). Specifically I do not have the data to test them on other electrode configurations.

**Comment by craddm** [comment]
Thanks, merged. Also fixed call to map as purrr wasn't in namespace - just added importFrom purrr Map as for some reason purrr has conflicts with dplyr and the warning messages were annoying.

I've also now added interactive_scalp, a Shiny gadget that allows you to choose specific electrodes to plot - check it out! 

Will try out some different electrode configurations when I get the chance.
