### ISSUE TITLE
OSX tests fail

### ISSUE THREAD

**Issue by adigherman** [craddm/eegUtils#32]
Dear Matt,

The test-ICA.R tests are failing on OSX. 

```> test_check("eegUtils")
── 1. Failure: topoplots for ICA work (@test-ICA.R#14)  ───────────────────────
Figures don't match: topographical-plot-for-sobi.svg


── 2. Failure: ICA timecourses work (@test-ICA.R#26)  ─────────────────────────
Figures don't match: timecourse-over-one-component.svg


── 3. Failure: component removal works (@test-ICA.R#39)  ──────────────────────
Figures don't match: removed-one-component.svg


── 4. Failure: component removal works (@test-ICA.R#41)  ──────────────────────
Figures don't match: reconstruct-all.svg
```
Any idea what is causing this? 

Thanks!

**Comment by craddm** [comment]
Hi Adi,

Not too sure - would have to see the figures generated on OSX to tell if it's a meaningful failure or just a trivial one. These tests can sometimes fail even with really trivial differences, which I suspect is what's happening here - I'll see if i can get a friendly OSX user to check it for me :) I've had trouble before with these specific tests failing on Appveyor for no obvious reason - the figures matched to the eye - so I may just disable them on Travis for now..

Cheers,
Matt

**Comment by muschellij2** [comment]
Looks like these are fixed via develop branch, probably fine to close - also the tests now skip on travis (don't know if that's great, but will fix these).
