### ISSUE TITLE
eeg_filter() should have parameter to adapt demeaning behavior

### ISSUE THREAD

**Issue by eioe** [craddm/eegUtils#36]
when using eeg_filter() on non-raw data (e.g., for plotting) it would be handy to manipulate (or at least deactivate) the demeaning feature of the function. 
In a concrete case: when lp-filtering epoched data for plotting, epochs with high amplitude slow negative potentials (lasting for the bigger part of the epoch) were "pushed upwards", i.e. baseline signal was constant above x-axis. For such a case, it would be good to be able to either deactivate the demeaning or have a parameter that is forwarded to rm_baseline() to specify the baseline time window (i.e., time_lim).

**Comment by craddm** [comment]
added a "demean" parameter to eeg_filter() on the develop branch
