### ISSUE TITLE
Support for file formats other than BDF/EDF

### ISSUE THREAD

**Issue by craddm** [craddm/eegUtils#5]
Currently import_raw() only handles BDF/EDF files, thanks to the edfReader package. I'd like to extend support to other file formats, such as those from EGI or Neuroscan systems.

**Comment by bnicenboim** [comment]
I have a bunch of .eeg files from BrainVision Data Exchange Marker File. I'll see if I manage to export them, and will add support if so.

**Comment by bnicenboim** [comment]
This could be helpful: https://github.com/mne-tools/mne-python/blob/73c80d65dda142165f3bbc27a4d3893244df150a/mne/io/brainvision/brainvision.py

I'll see if I manage to do something (probably in a couple of weeks after I finish some urgent matters)

**Comment by craddm** [comment]
Thanks! I've just added (limited) support for Neuroscan .CNT files (32-bit ones at least), which I had lying around to try out, so other file formats would be great! Need to do some more testing on the .CNT files but it's a start.

**Comment by bnicenboim** [comment]
Hi, so finally, I'm working on binary .dat files produced by Brain vision, which seem straightforward to read. But I wanted to understand better the format that you're already using. Would you mind sharing a .bdf file so that I try the package? You mention "S123ExteroSSDTB1.bdf" but it's not available in your github.

**Comment by craddm** [comment]
Hi @bnicenboim, 

Funnily enough - I'd just been thinking about how best to standardise the structures I'm building - here's a link to a bit of a description of the [eeg_data structure](https://craddm.github.io/eegUtils/articles/data_structures.html)

Here's a link for some demo data on Biosemi's [website](https://www.biosemi.com/faq/file_format.htm) - I can give you some other data if you need it, but that should work just to demonstrate the format etc.
Cheers,
Matt

**Comment by bnicenboim** [comment]
> Funnily enough - I'd just been thinking about how best to standardise the structures I'm building - here's a link to a bit of a description of the eeg_data structure

Specifically I wanted to know the name of the columns of `signals` inside `eeg_data`. And also where do you store information about the electrodes? (like where they were in the cap)

> Here's a link for some demo data on Biosemi's website - I can give you some other data if you need it, but that should work just to demonstrate the format etc.

But can you send me any .bdf file so that I can test your functions? (Or better yet include it in the package --maybe at a later date if it's too complicated)

**Comment by bnicenboim** [comment]
Thanks for the info!
But I don't even know how the  EEGLAB .set looks like, I have .vmrk and vhdr files with meta data. 

In any case, I only have .dat and .eeg around. So maybe you can upload a bdf with a minute of recordings? (or even less) and maybe also a .set file. You can also DM me in twitter or email me with a link in the meanwhile.

**Comment by craddm** [comment]
TBH the demo files on the Biosemi page I linked earlier (they're linked right at the bottom - I should have specified) should already be useable for many things - about the only thing that won't work out of the box should be topographies... actually even that might work if you used `electrode_locations(data_you_loaded, montage = 'biosemi64alpha')`

[Here's a direct link](https://www.biosemi.com/download/BDFtestfiles.zip)
