### ISSUE TITLE
Add `S2B1.bdf` to package

### ISSUE THREAD

**Issue by muschellij2** [craddm/eegUtils#55]
Can you add `S2B1.bdf` to the package if it's to be used for vignettes/readme?

**Comment by craddm** [comment]
No - it's way too large should I ever choose to get this on CRAN - there's a 5 mb package size limit. Hence the vignettes shouldn't be rebuilt on other machines.

I'm planning to move to a different file for the vignettes that is one I am in a better position to make publicly available for download, at least.

**Comment by muschellij2** [comment]
Got it - could use figshare and download on-demand.

**Comment by craddm** [comment]
I've switched to a different file `Matt-task-spatcue.bdf`, which is available from OSF for the main "Getting Started" vignette. The code in the vignette should download it if it's missing.
