### ISSUE TITLE
Tibble 2.0 issues

### ISSUE THREAD

**Issue by muschellij2** [craddm/eegUtils#56]
Getting warnings when running `electrode_locations`:
```
The `x` argument of `as_tibble.matrix()` must have column names if `.name_repair` is omitted as of tibble 2.0.0.
Using compatibility `.name_repair`.
```

**Comment by craddm** [comment]
This has been driving me nuts, i was getting this error already for something but there was literally nowhere I could find that I was doing anything to actually cause this warning... I'll dig into it again!

**Comment by craddm** [comment]
Ok, I've fixed a few of these errors that were cropping up in my tests, but I can't get this to happen with `electrode_locations()`. Could you give me a bit more detail about when it happens?

**Comment by muschellij2** [comment]
I just saw it randomly.  It's not an error, but more a warning.  Also - you have > 20 dependencies.  This is quite a bit.  Not a huge issue, but can't get on CRAN with this many really.  Do you know which can be moved to suggests because 1-2 functions need it?

**Comment by muschellij2** [comment]
Also, this errors on Travis: https://travis-ci.com/github/muschellij2/eegutils and Appveyor

**Comment by craddm** [comment]
> Also, this errors on Travis: https://travis-ci.com/github/muschellij2/eegutils and Appveyor

Currently dev branch is building fine on mine (and I hadn't seen your errors at any point AFAIK)

> I just saw it randomly. It's not an error, but more a warning. Also - you have > 20 dependencies. This is quite a bit. Not a huge issue, but can't get on CRAN with this many really. Do you know which can be moved to suggests because 1-2 functions need it?

I'll keep an eye out for it but I can't see an obvious reason for it to come up with `electrode_locations()`.

About the number of dependencies. There's a few I might be able to trim. I've cut `viridis` from the dev branch, since those scales are now integrated intro `ggplot2` anyway. `ini` I can drop when I have to time to rewrite the bit I need from it. I know this as an upcoming check on CRAN, but it's kinda weird and arbitrary. 1) A lot of the dependencies are kind of nested; if i'm importing `dplyr` there's no point avoiding importing `tibble` since `dplyr` depends on `tibble`; but if, for example, I have 20 imports already and import `tibble` I'm suddenly importing too many packages? 2) a number of the packages are always part of the base R installation anyway. 3) sometimes it's better to use a well-maintained dependency rather than roll-your-own code, even if it's only for one or two functions.

**Comment by muschellij2** [comment]
1.  These are CRAN policies, but they generally are best heeded.
2.  As you state, the dependencies are a bit nested, therefore 20 packages can really rely on hundreds of other packages, increasing risk for failure.
3.  I agree with the roll your own code, but it recommends to put the lighter deps into Suggests and use `requireNamespace` to check the presence of the package and an helpful error message.

Either way, it's fine for now, but I think a more nuanced dependency structure may be useful long term.

**Comment by craddm** [comment]
> 1. These are CRAN policies, but they generally are best heeded.
> 2. As you state, the dependencies are a bit nested, therefore 20 packages can really rely on hundreds of other packages, increasing risk for failure.

Sure, but the point is also that the number of further dependencies doesn't necessarily go up when you add another dependency directly. I think a hard limit is a bit odd...

> 3. I agree with the roll your own code, but it recommends to put the lighter deps into Suggests and use `requireNamespace` to check the presence of the package and an helpful error message.
> 
> Either way, it's fine for now, but I think a more nuanced dependency structure may be useful long term.

I already tend to do number 3. However, I am also considering trying to split the package into smaller packages to make some aspects more manageable...

**Comment by a-hurst** [comment]
> Either way, it's fine for now, but I think a more nuanced dependency structure may be useful long term.

@craddm Just as an interested onlooker (getting back into MNE for an EEG project and wishing I could be doing it all in R instead), one possibility for this would be splitting the project into a back-end package with all the core import/processing/plotting functions (eegUtils) and a separate front-end package for all the interactive stuff (shinyEEG or something). That's how RStan does it (with the separate shinystan package), and it would mean being able to drop shiny, miniUI, and plotly as dependencies (all dependency-heavy themselves), and give you room to expand on dependencies when further developing front-end UI tools.

**Comment by craddm** [comment]
@a-hurst Thanks for the suggestion! that's very much in line with what I have in mind; I've started doing something like that already, but not much bandwidth at the moment. There'll still be another release of this mega-package first though.

**Comment by craddm** [comment]
Closing this as as far as I can tell all the `tibble` issues have now been handled!
