### ISSUE TITLE
Support for .wav files?

### ISSUE THREAD

**Issue by dgrmunch** [craddm/eegUtils#60]
Would this library support wave files for single channels like BackyardBrains SpikerShield?
https://backyardbrains.com/products/heartandbrainspikershieldbundle
If not, is there any way to transform this kind of input into an accepted data format?

**Comment by craddm** [comment]
Probably possible - I know nothing about the system! Does it have additional files that go along with the .wavs with something like event triggers...? It might also be that the seewave package'll do what you need to do with it - http://rug.mnhn.fr/seewave/

**Comment by dgrmunch** [comment]
Yes. The wav files include one channel per eeg channel. And additionally you can have a .txt file with the events.

**Comment by craddm** [comment]
If you've got an example I could have a look

**Comment by craddm** [comment]
Closing as not heard back about this - happy to reopen
