### ISSUE TITLE
topoplot convex hull?

### ISSUE THREAD

**Issue by craddm** [craddm/eegUtils#62]
add convex_hull as interp limit option?

**Comment by TheY3TI** [comment]
Hi

I needed exactly such an option for my research, as extrapolating outside of the convex hull defined by the channel locations would cause misinterpretation.
I've made a very rudimentary modification to the geom_topo code. However, I'm struggling to make it into a nice interp_limit option as you had also mentioned above (seems to give an error when using the new argument value), which causes the tests to fail. I though I'd share my code here ([PR #150](https://github.com/craddm/eegUtils/pull/150)) hoping that someone can help with that.

Kind regards
