### ISSUE TITLE
vignettes and help

### ISSUE THREAD

**Issue by bnicenboim** [craddm/eegUtils#9]
Hi,

It seems that the vignette by @erzk is not available
https://github.com/craddm/eegUtils/pull/8

And in the website, only data structure is available in the articles menu
https://craddm.github.io/eegUtils/articles/data_structures.html

but I found eegUtils-intro.html buried in the git

**Comment by craddm** [comment]
eegUtils-intro was a detailed intro document I worked on a while back, but killed off for the time being due to filesize issues with the example data I was using, meaning to come back to it at some point. @erzk s vignette is now included.
