### ISSUE TITLE
File format change for EEGLAB2021

### ISSUE THREAD

**Issue by FlorianScharf** [craddm/eegUtils#91]
Hi,
The newest revision of EEGLAB came with a fundamental change: instead of the EEG structure, its content is saved in the set-Files.

When you apply readMAT to an old set-File everything in the list is nested within "EEG", when you load an EEGLAB2021 set-File, you are directly in a list with 41 elements. 

The easiest way to assure compatibility across versions would be to check for the existence of "EEG" in the upper level of the hierarchy and if it is not there, create it and put the list content into it manually.

Hope this description of the problem is clear.

Best,
Florian

**Comment by craddm** [comment]
Hi,

Thanks for the report! Yes, I see what you mean. I hadn't noticed that about the new format, although I knew they'd changed it! In the develop branch I've added support for the newer Matlab file formats, which are based on HDF5 - HDF5 isn't supported at all by `readMat()` - and if the EEGLAB2021 set file is saved in *that* format, which is the default they're trying to enforce (IIRC), there should be no problem. I'll see about adding a fix for the situation you describe too...

Cheers,
Matt

**Comment by craddm** [comment]
Now implemented and merged with master in #87
