### ISSUE TITLE
Suggestion: tfr - foi on the log scale?

### ISSUE THREAD

**Issue by mattansb** [craddm/eegUtils#93]
Currently the frequencies are spaced linearly, but it is often useful to have them spaced logarithmically.

``` r
foi <- c(4, 30)
n_freq <- 10

# lin space
seq(foi[1], foi[2], length.out = n_freq)
#>  [1]  4.000000  6.888889  9.777778 12.666667 15.555556 18.444444 21.333333
#>  [8] 24.222222 27.111111 30.000000

# log space
exp(seq(log(foi[1]), log(foi[2]), length.out = n_freq))
#>  [1]  4.000000  5.003674  6.259189  7.829735  9.794361 12.251948 15.326189
#>  [8] 19.171814 23.982377 30.000000
```

<sup>Created on 2021-06-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by craddm** [comment]
I'll stick this on the to-do list, should be easy enough - I intended to let people specify the freqs directly as well as just providing a range. (I seem to remember it being a bit of a pain for plotting with geom_raster(), though)

**Comment by mattansb** [comment]
> (I seem to remember it being a bit of a pain for plotting with geom_raster(), though)

Yeah, but is see that in the plot method you have an interpolation option, so that might do the trick (:

**Comment by craddm** [comment]
The issue is something to do with unequal tile sizes - the interpolate option just smooths the surface a bit, it doesn't actually handle irregularly spaced grids etc (which is what log spacing creates).  But I digress - should be able to figure it out!

**Comment by craddm** [comment]
Now implemented on the develop branch!

**Comment by mattansb** [comment]
Thanks!
