### ISSUE TITLE
Suggestion: add docs for the various S3 classes

### ISSUE THREAD

**Issue by mattansb** [craddm/eegUtils#95]
In order to expand on eegUtils, it would make it super helpful to understand what the various objects can be expected to hold (:

**Comment by craddm** [comment]
https://craddm.github.io/eegUtils/articles/data_structures.html  has some info on these lines - I'll improve/update it Soon™

**Comment by mattansb** [comment]
Ohhhhhh I missed that because I was looking in the function list 😅 oops!

**Comment by craddm** [comment]
It could definitely be better so that's still going on the list!

**Comment by mattansb** [comment]
Is there a reason that only for the `eeg_tfr` class the `signals` slot is an array (vs a (timeXepochs)Xchannels data frame)? 
I assume an array would be more memory efficient? (cf. [`{cubelyr}`](https://cran.r-project.org/web/packages/cubelyr/))

**Comment by craddm** [comment]
With `eeg_tfr` it made much more sense to do the transformations in an array internally, and then it ended up being easier to interact with if it stays an array. If I could start over then I'd probably just use arrays for everything, but I didn't really expect to go so far with it all... I did start another test package that was for switching current formats to arrays. But memory-wise tbh it hardly seems to make much difference when I've tried testing it all, and I haven't the time to rewrite everything and ensure backward compatibility etc
